resolver: lts-15.15
packages:
- typed-uuid
- genvalidity-typed-uuid
extra-deps:
- github: NorfairKing/yamlparse-applicative
  commit: 1a42f1b03f7b59b2ea1ff75a59c5ba4e1f973065
  subdirs:
  - yamlparse-applicative
- github: NorfairKing/validity
  commit: c38fc635f98580548f82314504e9f8742519f94d
  subdirs:
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-criterion
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-hspec-binary
  - genvalidity-hspec-cereal
  - genvalidity-hspec-hashable
  - genvalidity-hspec-optics
  - genvalidity-path
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector


nix:
  path: [ "nixpkgs=https://github.com/NixOS/nixpkgs/archive/e3a2247046d4de66b9b193a6ab3ff040fa3da86d.tar.gz" ]
  add-gc-roots: true
  packages:
  - zlib

