name: typed-uuid
version: 0.2.0.0
github: "NorfairKing/typed-uuid"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright: (c) 2018-2022 Tom Sydney Kerckhove"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Phantom-Typed version of UUID
category:            Data

dependencies:
- aeson
- autodocodec
- base >= 4.11 && < 5
- binary
- bytestring
- deepseq
- hashable
- http-api-data
- random
- text
- uuid >=1.3 && <1.4
- validity
- validity-uuid >=0.0

library:
  source-dirs: src
