name:                typed-uuid
version:             0.0.0.0
github:              "NorfairKing/typed-uuid"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd.kerckhove@gmail.com"
copyright:           "Copyright: (c) 2018 Tom Sydney Kerckhove"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Phantom-Typed version of UUID
category:            Data

description:         Please see the README on Github at <https://github.com/NorfairKing/typed-uuid#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- binary
- bytestring
- deepseq
- hashable
- http-api-data
- random
- text
- uuid >=1.3 && <1.4
- validity
- validity-uuid >=0.0 && <0.1

library:
  source-dirs: src
  exposed-modules:
    Data.UUID.Typed
