name:                typed-uuid
version:             0.1.0.0
github:              "NorfairKing/typed-uuid"
license:             MIT
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright: (c) 2018-2019 Tom Sydney Kerckhove"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Phantom-Typed version of UUID
category:            Data

description:         Please see the README on Github at <https://github.com/NorfairKing/typed-uuid#readme>

dependencies:
- aeson
- base >= 4.11 && < 5
- binary
- bytestring
- deepseq
- hashable
- http-api-data
- random
- text
- uuid >=1.3 && <1.4
- validity
- validity-uuid >=0.0
- yamlparse-applicative

library:
  source-dirs: src
  exposed-modules:
    Data.UUID.Typed
